package org.jarogoose.archigen.core.template.storage;

import java.io.File;
import org.jarogoose.archigen.core.Paths;
import org.jarogoose.archigen.core.template.ArcTemplate;
import org.jarogoose.archigen.web.config.domain.model.dto.Config;
import org.jarogoose.archigen.web.generate.domain.model.dto.Domain;

public class LoaderTemplate implements ArcTemplate {

  public static final String TEMPLATE = """
  package {{project-path}}.feature.{{root-name}}.storage;

  import {{project-path}}.feature.{{root-name}}.domain.exception.{{feature-name}}Exception;
  import org.springframework.stereotype.Repository;

  /**
   * {@link {{feature-name}}Loader} executes and validate CRUD operations data.
   * <p>
   * Loader is responsible for:
   * <li> entity-to-dto mapping </li>
   * <li> entity validation </li>
   * <li> all method name are in CRUD style (Create, Read, Update, Delete) </li>
   * <li> query calls to storage </li>
   *
   * @author Generated by {{author-name}}
   */
  @Repository
  public class {{feature-name}}Loader {

    private final {{feature-name}}Storage {{feature-name-lowercase}}Storage;

    public {{feature-name}}Loader() {
      this.{{feature-name-lowercase}}Storage = {{feature-name-lowercase}}Storage;
    }

    public void create{{feature-name}}() {
      throw new {{feature-name}}Exception("Auto-generated method stub");
    }

    public void readAll{{feature-name}}() {
      throw new {{feature-name}}Exception("Auto-generated method stub");
    }
  }

  """;

  private final Config config;
  private final Domain domain;

  public LoaderTemplate(Config config, Domain domain) {
    this.config = config;
    this.domain = domain;
  }

  @Override
  public String content() {
    String template = TEMPLATE;

    template = replaceAuthorName(template, config.author());
    template =
      replaceProjectPath(template, config.artefact(), config.project());
    template = replaceRootName(template, domain.root());
    template = replaceFeatureName(template, domain.feature());
    template = replaceFeatureNameLowered(template, domain.feature());

    return template;
  }

  @Override
  public File file() {
    return new File(
      Paths.STORAGE_PATH.get(
        config,
        domain.root(),
        domain.feature(),
        "Loader",
        false
      )
    );
  }
}
