version: '3.8'
services:
  # Mongo DB
  arc-dev-mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: arcadmin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_ROOT_DATABASE: archigen
      MONGO_DB_USERNAME: goose
      MONGO_DB_PASSWORD: goose
      # MONGO_DB_USERNAME: user
      # MONGO_DB_PASSWORD: secret
  # Mongo Express UI 
  arc-dev-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9200:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: arcadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://arcadmin:admin@arc-dev-mongodb:27017/
    depends_on:
      - arc-dev-mongodb
  # Spring Boot Server
  arc-dev-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9100:8080
    environment:
      - SERVER_PORT=8080
    depends_on:
      - arc-dev-mongodb 
  # Ionic App NGINX Server
  arc-dev-ui:
    build:
      context: ../archigen-ui
      dockerfile: Dockerfile
    ports:
      - 9000:80
