version: '3.8'
services:
  # Mongo DB
  arc-dev-mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prodadmin
      MONGO_INITDB_ROOT_PASSWORD: prodpassword
      MONGO_INITDB_ROOT_DATABASE: admin
    volumes:
      - arc-dev-db:/data/db
  # Mongo Express UI 
  arc-dev-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9200:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: prodadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: prodpassword
      ME_CONFIG_MONGODB_URL: mongodb://prodadmin:prodpassword@arc-dev-mongodb:27017/
    depends_on:
      - arc-dev-mongodb
  # Spring Boot Server
  arc-dev-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9100:8080
    environment:
      - SERVER_PORT=8080
    depends_on:
      - arc-dev-mongodb 
  # Ionic App NGINX Server
  arc-dev-ui:
    build:
      context: ../archigen-ui
      dockerfile: Dockerfile
    ports:
      - 9000:80

volumes:
  arc-dev-db:
