version: '3.8'
name: archigen

services:
  ### Mongo DB ###
  arc-dev-mongodb:
    container_name: arc-dev-mongodb
    image: mongo
    ports:
      - 9120:27017
    restart: always
    env_file:
      - ./.env/mongodb-dev.env
    volumes:
      - arc-dev-db:/data/db

  ### Spring Boot Server ###
  arc-dev-server:
    container_name: arc-dev-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9110:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8080
    depends_on:
      - arc-dev-mongodb

  ### Ionic App NGINX Server ###
  arc-dev-ui:
    container_name: arc-dev-web
    build:
      context: ../archigen-ui
      dockerfile: Dockerfile
    ports:
      - 9100:80

### Volumes ###
volumes:
  arc-dev-db:
