package org.jarogoose.archigen.core.template;

import static org.springframework.util.StringUtils.capitalize;
import java.io.File;
import org.jarogoose.archigen.core.domain.Domain;
import org.jarogoose.archigen.core.util.Paths;
import org.jarogoose.archigen.web.domain.Config;

public class LoaderTemplate implements ArcTemplate {

  public static final String TEMPLATE = """
  package {{project-path}}.feature.{{root-name}}.storage;

  import {{project-path}}.feature.{{root-name}}.domain.exception.{{feature-name}}Exception;
  import org.springframework.stereotype.Repository;
  
  /**
   * {@link {{feature-name}}Loader} executes and validate CRUD operations data.
   * <p>
   * Loader is responsible for:
   * <li> entity-to-dto mapping </li>
   * <li> entity validation </li>
   * <li> all method name are in CRUD style (Create, Read, Update, Delete) </li>
   * <li> query calls to storage </li>
   *
   * @author Generated by {{author-name}}
   */
  @Repository
  public class {{feature-name}}Loader {
  
    private {{feature-name}}Storage {{feature-name-lowercase}}Storage;
  
    public {{feature-name}}Loader() {
      this.{{feature-name-lowercase}}Storage = {{feature-name-lowercase}}Storage;
    }
  
    public void create{{feature-name}}() {
      throw new {{feature-name}}Exception("Auto-generated method stub");
    }
  
    public void readAll{{feature-name}}() {
      throw new {{feature-name}}Exception("Auto-generated method stub");
    }
  }
  
  """;

  private final Config config;
  private final Domain domain;
  
  public LoaderTemplate(Config config, Domain domain) {
    this.config = config;
    this.domain = domain;
  }

  @Override
  public String content() {
    final String projectPath = String.format(
      "%s.%s",
      config.artefact(),
      config.project()
    );
    final String featureName = capitalize(domain.feature());
    final String featureNameLowercase = domain.feature();

    String template = TEMPLATE;

    template = template.replace("{{author-name}}", config.author());
    template = template.replace("{{project-path}}", projectPath);
    template = template.replace("{{root-name}}", domain.root());
    template = template.replace("{{feature-name}}", featureName);
    template = template.replace("{{feature-name-lowercase}}", featureNameLowercase);

    return template;
  }

  @Override
  public File file() {
    return new File(Paths.STORAGE_PATH
      .get(config, domain.root(), domain.feature(), "Loader"));
  }
}
