package org.jarogoose.archigen.service;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("[UNIT TEST] Controller template generation")
class ControllerTemplateTest {

  private static final String EXPECTED = """
      package com.jarogoose.enenbi.feature.metabolism.control;
        
      import com.jarogoose.enenbi.event.Event;
      import com.jarogoose.enenbi.feature.metabolism.api.DailyMetabolicActivityFacade;
      import com.jarogoose.enenbi.feature.metabolism.domain.model.request.AddDailyMetabolicActivityRequest;
      import com.jarogoose.enenbi.feature.metabolism.domain.exception.DailyMetabolicActivityNotFoundException;
      import com.jarogoose.enenbi.feature.metabolism.domain.model.request.ModifyDailyMetabolicActivityRequest;
      import com.jarogoose.enenbi.feature.metabolism.domain.model.request.SearchDailyMetabolicActivityRequest;
      import com.jarogoose.enenbi.feature.metabolism.domain.model.request.ShowAllDailyMetabolicActivitiesRequest;
      import com.jarogoose.enenbi.feature.metabolism.domain.model.request.RemoveDailyMetabolicActivityRequest;
      import com.jarogoose.enenbi.rest.EnenbiController;
      import lombok.extern.slf4j.Slf4j;
      import org.springframework.http.ResponseEntity;
      import org.springframework.web.bind.annotation.DeleteMapping;
      import org.springframework.web.bind.annotation.GetMapping;
      import org.springframework.web.bind.annotation.PostMapping;
      import org.springframework.web.bind.annotation.PutMapping;
      import org.springframework.web.bind.annotation.RequestBody;
      import org.springframework.web.bind.annotation.RequestMapping;
      import org.springframework.web.bind.annotation.RestController;
        
      @Slf4j
      @RestController()
      @RequestMapping("user-ui/metabolism-api")
      public class DailyMetabolicActivityController implements EnenbiController {
        
        private final DailyMetabolicActivityFacade facade;
        
        public DailyMetabolicActivityController(DailyMetabolicActivityFacade facade) {
          this.facade = facade;
        }
        
        @Event
        @PostMapping("add-daily-metabolic-activity")
        public ResponseEntity<Object> addDailyMetabolicActivity(@RequestBody AddDailyMetabolicActivityRequest request) {
          // TODO Autogenerated
          try {
            facade.addDailyMetabolicActivity(request);
            return ok("Success");
          } catch (Exception e) {
            return internalServerError();
          }
        }
        
        @Event
        @PutMapping("modify-daily-metabolic-activity")
        public ResponseEntity<Object> modifyDailyMetabolicActivity(@RequestBody ModifyDailyMetabolicActivityRequest request) {
          // TODO Autogenerated
          try {
            facade.modifyDailyMetabolicActivity(request);
            return ok("Success");
          } catch (Exception e) {
            return internalServerError();
          }
        }
        
        @Event
        @PostMapping("search-daily-metabolic-activity")
        public ResponseEntity<Object> searchDailyMetabolicActivity(@RequestBody SearchDailyMetabolicActivityRequest request) {
          // TODO Autogenerated
          try {
            var response = facade.searchDailyMetabolicActivity(request);
            return ok("Success", response);
          } catch (Exception e) {
            return internalServerError();
          }
        }
        
        @Event
        @PostMapping("show-all-daily-metabolic-activities")
        public ResponseEntity<Object> showAllDailyMetabolicActivities(@RequestBody ShowAllDailyMetabolicActivitiesRequest request) {
          // TODO Autogenerated
          try {
            var response = facade.showAllDailyMetabolicActivities(request);
            return ok("Success", response);
          } catch (Exception e) {
            return internalServerError();
          }
        }
        
        @Event
        @DeleteMapping("remove-daily-metabolic-activity")
        public ResponseEntity<Object> removeDailyMetabolicActivity(@RequestBody RemoveDailyMetabolicActivityRequest request) {
          // TODO Autogenerated
          try {
            facade.removeDailyMetabolicActivity(request);
            return ok("Success");
          } catch (Exception e) {
            return internalServerError();
          }
        }
        
      }
        
      """;

  @Test
  @DisplayName("[FEATURE] Controller class generated and formatted as expected")
  public void generateControllerClass() {
    ControllerTemplate template = new ControllerTemplate();
    String actual = template.createTemplate(Given.dailyMetabolicActivityDomain());

    Then.validTemplate(actual, EXPECTED);
  }

}
