spring:
  data:
    mongodb:
      username: 'jaro'
      password: 'goose'
      authentication-database: admin
      database: archigen-test
      port: 9202
      host: localhost
      auto-index-creation: true
