server:
  port: 8000

spring:
  data:
    mongodb:
      username: 'arcadmin'
      password: 'admin'
      # authentication-database: admin
      database: archigen
      port: 27017
      host: localhost
      auto-index-creation: true
