server:
  port: 8000

spring:
  data:
    mongodb:
      username: 'prodadmin'
      password: 'prodpassword'
      authentication-database: admin
      database: archigen
      port: 27017
      host: arc-mongodb
      auto-index-creation: true
