spring:
  data:
    mongodb:
      username: 'devadmin'
      password: 'devpassword'
      authentication-database: admin
      database: archigen
      port: 27017
      host: arc-dev-mongodb
      auto-index-creation: true
