spring:
  data:
    mongodb:
      username: 'goose'
      password: 'goose'
      authentication-database: admin
      database: archigen-test
      port: 27017
      host: localhost
      auto-index-creation: true
